# Generated by Django 4.1 on 2022-08-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='libele',
            field=models.CharField(max_length=100),
        ),
    ]
