# Generated by Django 4.1 on 2022-08-13 15:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_about_orderservice_reseausocial_service_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='img_under_site')),
                ('libele', tinymce.models.HTMLField()),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('price', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderService',
        ),
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.FileField(default=1, upload_to='img_service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='picture',
            field=models.FileField(upload_to='img_site'),
        ),
    ]
